language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "fab setup"
# command to run tests
script:
  - "fab lint"
  - "fab test"
# heroku deployment
deploy:
  run:
    - "fab setup"
  provider: heroku
  api_key:
    secure: HhPDZClTOyytpeAcDa5e7eZKbYXmoRJHzPaOjGL0zIkwW1paavCAg4YCgTlpYoEew5VkEA3608jaza9exlnZ6mJ9SWIg63Fbtecw3thJ+I/CLw16H24lz9438ulXAa30jkR4CBJ5cX7CDzwVzd4QRiQ68Vd7WLFsnDOAOKLOKDY=
  app: restfultodo
  on:
    repo: w0rm/todo
